"""Governance-footprint primitives shared by bootstrap hosts and rule generators."""

from __future__ import annotations

import hashlib
import os
from typing import Any, Callable

MEMORY_ONLY_HOOKS = frozenset({"memory_pretool_block.py", "memory_posttool_audit.py"})
PROFILE_MARKER_PREFIX = "<!-- TAUSIK:GOVERNANCE-PROFILE:"
GENERATED_HASH_PREFIX = "<!-- TAUSIK:GENERATED-SHA256:"
DYNAMIC_START = "<!-- DYNAMIC:START -->"
DYNAMIC_END = "<!-- DYNAMIC:END -->"

MEMORY_ONLY_RULES = """## Governance profile: memory-only

This project explicitly keeps TAUSIK as a project-memory and retrieval layer, not as a
task/verification workflow. Do not open or close TAUSIK tasks or sessions, declare scope,
or run TAUSIK verify unless the owner asks for that operation.

Retained:
- project memory, decisions and logs through the `tausik-project` MCP/CLI;
- code search and retrieval through `codebase-rag`;
- `memory_pretool_block.py` and `memory_posttool_audit.py`, which keep project knowledge
  out of host-private memory sinks and audit memory writes.

Not guaranteed in this profile: QG-0/QG-2 enforcement, task/scope write gates, automatic
session lifecycle, verification receipts, secret scanning, push protection or usage hooks.
Use the repository's own tests and operational controls for those properties.

## Memory routing

- Search project memory before guessing an established project fact.
- Store project-specific facts in TAUSIK project memory; store reusable tool knowledge in
  shared knowledge; keep only personal preferences in host auto-memory.
- Never put secrets, client names or project paths into shared knowledge.

The profile changes local governance wiring only. It does not delete the TAUSIK database,
memory, history, MCP servers or RAG index.
"""


def governance_profile_marker(profile: str) -> str:
    return f"{PROFILE_MARKER_PREFIX}{profile} -->"


def memory_only_body(header: str, response_language: str, answer_shape: str) -> str:
    """Compose the small rule pack without importing the full template module."""
    return "\n".join(
        (
            header,
            governance_profile_marker("memory-only"),
            MEMORY_ONLY_RULES,
            response_language,
            answer_shape,
        )
    )


def filter_memory_hooks(
    hooks: dict[str, list[dict[str, Any]]], script_of: Callable[[dict[str, Any]], str]
) -> dict[str, list[dict[str, Any]]]:
    """Keep only the two memory scripts without copying host matcher semantics."""
    filtered: dict[str, list[dict[str, Any]]] = {}
    for event, entries in hooks.items():
        kept = []
        for entry in entries:
            memory_hooks = [
                hook for hook in entry.get("hooks", []) if script_of(hook) in MEMORY_ONLY_HOOKS
            ]
            if memory_hooks:
                kept.append({**entry, "hooks": memory_hooks})
        if kept:
            filtered[event] = kept
    return filtered


def _ownership_payload(content: str) -> str:
    """Return generated bytes whose hash ignores the mutable dynamic state body."""
    marker_start = content.find(GENERATED_HASH_PREFIX)
    marker_end = content.find(" -->", marker_start)
    payload = content
    if marker_start >= 0 and marker_end >= marker_start:
        remove_from = (
            marker_start - 1 if content[marker_start - 1 : marker_start] == " " else marker_start
        )
        payload = content[:remove_from] + content[marker_end + len(" -->") :]
    head, marker, rest = payload.partition(DYNAMIC_START)
    if marker:
        _, closing, tail = rest.partition(DYNAMIC_END)
        if closing:
            payload = head + DYNAMIC_START + "\n" + DYNAMIC_END + tail
    return payload


def _stamp_generated(content: str) -> str:
    digest = hashlib.sha256(_ownership_payload(content).encode("utf-8")).hexdigest()
    marker = f"{GENERATED_HASH_PREFIX}{digest} -->"
    first, separator, rest = content.partition("\n")
    return f"{first} {marker}\n{rest}" if separator else f"{content} {marker}\n"


def _is_pristine_generated(content: str) -> bool:
    if content.count(GENERATED_HASH_PREFIX) != 1:
        return False
    marker_start = content.find(GENERATED_HASH_PREFIX)
    marker_end = content.find(" -->", marker_start)
    if marker_end < marker_start:
        return False
    recorded = content[marker_start + len(GENERATED_HASH_PREFIX) : marker_end]
    actual = hashlib.sha256(_ownership_payload(content).encode("utf-8")).hexdigest()
    return recorded == actual


def _preserve_dynamic_state(generated: str, existing: str) -> str:
    """Carry mutable generated state across a pristine static refresh."""
    generated_start = generated.find(DYNAMIC_START)
    generated_end = generated.find(DYNAMIC_END, generated_start)
    existing_start = existing.find(DYNAMIC_START)
    existing_end = existing.find(DYNAMIC_END, existing_start)
    if min(generated_start, generated_end, existing_start, existing_end) < 0:
        return generated
    generated_body = generated_start + len(DYNAMIC_START)
    existing_body = existing_start + len(DYNAMIC_START)
    return (
        generated[:generated_body]
        + existing[existing_body:existing_end]
        + generated[generated_end:]
    )


def write_generated_rules(
    path: str, content: str, output_mode: str, governance_profile: str
) -> None:
    """Write only files whose ownership stamp still proves they are unmodified."""
    stamped = _stamp_generated(content)
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(stamped)
        return
    try:
        with open(path, encoding="utf-8") as f:
            existing = f.read()
    except (OSError, UnicodeError):
        from bootstrap_templates import warn_output_mode_not_applied

        warn_output_mode_not_applied(path, output_mode)
        return
    if existing == stamped:
        return
    managed = _is_pristine_generated(existing)
    if managed:
        refreshed = _preserve_dynamic_state(stamped, existing)
        if existing != refreshed:
            with open(path, "w", encoding="utf-8") as f:
                f.write(refreshed)
        return
    if governance_profile == "memory-only":
        print(
            f"  WARNING: governance_profile=memory-only was not applied to custom "
            f"{os.path.basename(path)}; remove or edit it explicitly."
        )
        return
    from bootstrap_templates import warn_output_mode_not_applied

    warn_output_mode_not_applied(path, output_mode)
