"""Регистрация MCP-серверов у Codex: блок ДОПИСЫВАЕТСЯ, чужой TOML не переписывается.

ФОРМАТ УСТАНОВЛЕН ПО РАБОТАЮЩЕМУ ФАЙЛУ, а не по документации (смена #241). В
`~/.codex/config.toml` на живой машине лежат секции вида ``[mcp_servers.<имя>]``
с ключами ``command`` и ``args`` и, при необходимости, подтаблицей
``[mcp_servers.<имя>.env]``. Проектный ``.codex/config.toml`` Codex тоже читает —
строка присутствует в его бинаре. Пишем именно в проектный: домашний каталог
пользователя не принадлежит bootstrap проекта.

ПОЧЕМУ ДОПИСЫВАНИЕ, А НЕ ПЕРЕЗАПИСЬ — ЭТО ОГРАНИЧЕНИЕ ЯЗЫКА, А НЕ ВКУС. В stdlib
Python 3.11 есть `tomllib` только на ЧТЕНИЕ; писателя TOML нет, а тянуть
зависимость в bootstrap нельзя. Разобрать файл и сериализовать обратно значило бы
потерять комментарии пользователя, порядок его секций и форму его же записей —
то есть ровно то, ради сохранения чего слово preserve-first вообще произносится.
Поэтому чтение служит одному вопросу: «наши серверы уже записаны?» — а запись,
если нужна, ДОПИСЫВАЕТ блок между маркерами и не трогает ни байта выше.

ПУТИ АБСОЛЮТНЫЕ, как и у хуков, и по той же измеренной причине: у Codex нет ни
одной переменной рабочей области. Интерпретатор тоже абсолютный — хост запускает
сервер сам, и запущенный из графической оболочки не обязан передать ему PATH.

СЕРВЕР, КОТОРОГО НЕТ НА ДИСКЕ, НЕ ЗАПИСЫВАЕТСЯ ВОВСЕ. Запись команды, которая не
запустится, хуже отсутствия записи: отсутствие видно, а мёртвая запись выглядит
настроенной — тот же класс, что `.codex/hooks.json` с нераскрываемой переменной.
"""

from __future__ import annotations

import os
import shutil
import tomllib

#: Имя проектного конфига Codex — то, что ищет сам хост.
CONFIG_FILE = "config.toml"

#: (имя сервера, путь относительно корня mcp/). Порядок — порядок записи.
_SERVERS = (
    ("tausik-project", os.path.join("project", "server.py")),
    ("codebase-rag", os.path.join("codebase-rag", "server.py")),
)

#: Границы нашего блока. По ним же он и опознаётся при повторном прогоне —
#: поэтому текст маркеров менять нельзя, не оставив хвоста у всех, кто уже
#: развернулся.
BEGIN = "# >>> TAUSIK MCP servers (generated by bootstrap --ide codex) >>>"
END = "# <<< TAUSIK MCP servers <<<"


def _fallback_python() -> str:
    for name in ("python3", "python"):
        found = shutil.which(name)
        if found:
            return os.path.abspath(found)
    return "python"


def _resolve_server(rel: str, target_dir: str, lib_dir: str | None) -> str | None:
    """Путь к server.py: сперва копия в профиле, затем канонический в библиотеке.

    ``None``, когда нет ни того ни другого, — и вызывающий тогда пропускает
    сервер, а не пишет команду, которой нечего запускать.
    """
    copied = os.path.join(target_dir, "mcp", rel)
    if os.path.isfile(copied):
        return copied
    if lib_dir:
        canonical = os.path.join(lib_dir, "harness", "claude", "mcp", rel)
        if os.path.isfile(canonical):
            return canonical
    return None


def _toml_string(value: str) -> str:
    """Строка TOML в базовой форме с экранированием обратной косой и кавычки.

    Достаточно для путей, а других значений здесь и не бывает. Обратная косая
    экранируется первой — иначе экранирование кавычки само окажется съеденным.
    """
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_block(
    project_dir: str,
    target_dir: str,
    venv_python: str | None,
    lib_dir: str | None,
) -> str:
    """Текст блока `[mcp_servers.*]`, готовый к дописыванию. Пустая строка — нечего писать."""
    python_exe = os.path.abspath(venv_python) if venv_python else _fallback_python()
    project_abs = os.path.abspath(project_dir)
    lines: list[str] = []
    for name, rel in _SERVERS:
        server = _resolve_server(rel, target_dir, lib_dir)
        if server is None:
            continue
        args = ", ".join(
            _toml_string(a) for a in (os.path.abspath(server), "--project", project_abs)
        )
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"command = {_toml_string(python_exe)}")
        lines.append(f"args = [{args}]")
        lines.append("")
    if not lines:
        return ""
    return "\n".join([BEGIN, *lines, END, ""])


def already_registered(text: str) -> bool:
    """Наш блок уже в файле. По маркеру, а не по имени сервера.

    По имени было бы хрупко в обе стороны: пользователь мог прописать
    `tausik-project` сам и своим способом — тогда наш блок ему не нужен, — а мог
    и не прописать, но упомянуть имя в комментарии.
    """
    return BEGIN in text


def register_mcp_servers(
    project_dir: str,
    target_dir: str,
    venv_python: str | None = None,
    lib_dir: str | None = None,
) -> tuple[str, int]:
    """Дописать блок в `<проект>/.codex/config.toml`. Возвращает (путь, сколько записано).

    Ноль записанных означает одно из двух и оба нормальны: блок уже там, либо ни
    одного server.py не нашлось. Файл при этом не трогается вовсе.
    """
    os.makedirs(target_dir, exist_ok=True)
    path = os.path.join(target_dir, CONFIG_FILE)
    existing = ""
    if os.path.isfile(path):
        try:
            with open(path, encoding="utf-8") as fh:
                existing = fh.read()
        except (OSError, UnicodeDecodeError) as e:
            print(f"  WARNING: {path} нечитаем ({e}) — MCP-серверы для Codex НЕ зарегистрированы.")
            return path, 0
    # РАЗБОР ДО ЗАПИСИ, а не только после. Файл, уже не разбираемый, Codex не
    # прочтёт и сам; дописать в него значило бы спрятать чужую поломку под своим
    # блоком и получить жалобу «TAUSIK сломал мне конфиг». Не трогаем и говорим.
    if existing.strip():
        try:
            tomllib.loads(existing)
        except tomllib.TOMLDecodeError as e:
            print(
                f"  WARNING: {path} не разбирается как TOML ({e}) — Codex не прочтёт его и "
                "без нас. MCP-серверы НЕ записаны; почини файл и повтори bootstrap."
            )
            return path, 0

    block = build_block(project_dir, target_dir, venv_python, lib_dir)
    if not block:
        print("  WARNING: ни одного server.py не найдено — MCP-серверы для Codex не записаны.")
        return path, 0

    if already_registered(existing):
        # Наш блок уже есть: перезаписать ЕГО, не дописывать второй и не
        # оставлять в нём сервер, которого больше нет (tausik-brain ушёл вместе с
        # Notion, решение #358). Чужой текст вокруг блока не трогается.
        start = existing.index(BEGIN)
        end_marker = existing.find(END, start)
        if end_marker < 0:
            print(f"  WARNING: в {path} есть начало блока TAUSIK без конца — файл не изменён.")
            return path, 0
        end = end_marker + len(END)
        if existing[end : end + 1] == "\n":
            end += 1
        updated = existing[:start] + block + existing[end:]
        if updated == existing:
            return path, 0
        try:
            parsed = tomllib.loads(updated)
        except tomllib.TOMLDecodeError as e:  # pragma: no cover — наш блок собран из литералов
            print(f"  WARNING: перегенерированный блок сломал бы {path} ({e}) — файл не изменён.")
            return path, 0
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(updated)
        return path, len(parsed.get("mcp_servers", {}))

    # Ровно одна пустая строка между чужим текстом и нашим блоком: без неё
    # секция приклеится к последней строке пользователя, а две подряд копятся с
    # каждым прогоном у того, кто блок удалял руками.
    separator = ""
    if existing and not existing.endswith("\n\n"):
        separator = "\n" if existing.endswith("\n") else "\n\n"
    updated = existing + separator + block
    try:
        parsed = tomllib.loads(updated)
    except tomllib.TOMLDecodeError as e:  # pragma: no cover — наш блок собран из литералов
        # Дописанное сломало разбор, а до нас файл читался: виноват НАШ текст.
        # Молча оставить его значило бы отдать пользователю конфиг, который его
        # хост не прочтёт, — поэтому файл не трогается вовсе.
        print(f"  WARNING: сгенерированный блок сломал бы {path} ({e}) — файл не изменён.")
        return path, 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(updated)
    return path, len(parsed.get("mcp_servers", {}))
