#!/usr/bin/env bash
# TAUSIK CLI wrapper — always uses .tausik/venv Python
# Generated by bootstrap. Do not edit manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Find scripts dir (claude or cursor)
if [ -d "$PROJECT_DIR/.claude/scripts" ]; then
    SCRIPTS="$PROJECT_DIR/.claude/scripts"
elif [ -d "$PROJECT_DIR/.cursor/scripts" ]; then
    SCRIPTS="$PROJECT_DIR/.cursor/scripts"
else
    echo "Error: no scripts dir found (.claude/scripts or .cursor/scripts)" >&2
    exit 1
fi

# Find Python: prefer .tausik/venv, fallback to system
if [ -f "$SCRIPT_DIR/venv/bin/python" ]; then
    PYTHON="$SCRIPT_DIR/venv/bin/python"
elif [ -f "$SCRIPT_DIR/venv/Scripts/python.exe" ]; then
    PYTHON="$SCRIPT_DIR/venv/Scripts/python.exe"
else
    PYTHON="python"
fi

exec "$PYTHON" "$SCRIPTS/project.py" "$@"
