@echo off
REM TAUSIK CLI wrapper — always uses .tausik/venv Python
REM Generated by bootstrap. Do not edit manually.

setlocal
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

REM Find scripts dir (claude / cursor / qwen / windsurf / codex)
set "SCRIPTS="
for %%I in (claude cursor qwen windsurf codex) do (
    if not defined SCRIPTS if exist "%PROJECT_DIR%\.%%I\scripts" set "SCRIPTS=%PROJECT_DIR%\.%%I\scripts"
)
if not defined SCRIPTS (
    echo Error: no scripts dir found (.claude/.cursor/.qwen/.windsurf/.codex \scripts) 1>&2
    exit /b 1
)

REM Find Python: prefer .tausik/venv
if exist "%SCRIPT_DIR%venv\Scripts\python.exe" (
    set "PYTHON=%SCRIPT_DIR%venv\Scripts\python.exe"
) else (
    set "PYTHON=python"
)

"%PYTHON%" "%SCRIPTS%\project.py" %*
