@echo off
REM TAUSIK CLI wrapper — always uses .tausik/venv Python
REM Generated by bootstrap. Do not edit manually.

setlocal
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

REM Find scripts dir
if exist "%PROJECT_DIR%\.claude\scripts" (
    set "SCRIPTS=%PROJECT_DIR%\.claude\scripts"
) else if exist "%PROJECT_DIR%\.cursor\scripts" (
    set "SCRIPTS=%PROJECT_DIR%\.cursor\scripts"
) else (
    echo Error: no scripts dir found 1>&2
    exit /b 1
)

REM Find Python: prefer .tausik/venv
if exist "%SCRIPT_DIR%venv\Scripts\python.exe" (
    set "PYTHON=%SCRIPT_DIR%venv\Scripts\python.exe"
) else (
    set "PYTHON=python"
)

"%PYTHON%" "%SCRIPTS%\project.py" %*
