@echo off
REM TAUSIK CLI wrapper — always uses .tausik/venv Python
REM Generated by bootstrap. Do not edit manually.

setlocal
set "SCRIPT_DIR=%~dp0"
set "PROJECT_DIR=%SCRIPT_DIR%.."

REM Force UTF-8 stdio so Unicode output (Cyrillic, checkmarks) never hits a
REM cp1251/cp1252 console encoder and raises UnicodeEncodeError on Windows.
set "PYTHONUTF8=1"

REM Hand the untouched command line to python. cmd.exe parses >, <, &, | and ^
REM out of the line BEFORE this file runs, so %* can arrive truncated while the
REM command still reports success (measured: "48->49" reaches python as "48-",
REM rc 0, output diverted into a stray file). The environment survives that
REM parser, so cmdline_fidelity.py compares the two and refuses on a mismatch.
REM DELAYED expansion is not a style choice: %CMDCMDLINE% carries quotes, and
REM the quotes in a plain set "X=%CMDCMDLINE%" close the protecting pair early,
REM so a > inside the value redirects the set line itself and the value arrives
REM already truncated (measured: "SCHEMA 48->49 next" stored as "SCHEMA 48-
REM next"). !CMDCMDLINE! is substituted AFTER the line is parsed for operators.
REM The second setlocal turns delayed expansion back off — it inherits the
REM variable, and leaving it on would eat an exclamation mark inside %*.
REM Empty when a human runs the wrapper from an interactive shell: there
REM %CMDCMDLINE% is the shell's own startup line and names no arguments.
setlocal EnableDelayedExpansion
set "TAUSIK_RAW_CMDLINE=!CMDCMDLINE!"
setlocal DisableDelayedExpansion

REM Find scripts dir. IDE list injected from bootstrap_config.IDE_DIRS
REM (single source of truth) by install_cli_wrapper.
set "IDE_LIST=__IDE_LIST__"
set "SCRIPTS="
for %%I in (%IDE_LIST%) do (
    if not defined SCRIPTS if exist "%PROJECT_DIR%\.%%I\scripts" set "SCRIPTS=%PROJECT_DIR%\.%%I\scripts"
)
REM goto (not an inline block) so literal parens in the error text can't
REM prematurely close the if-block and make exit unconditional. (v153 Windows fix)
if not defined SCRIPTS goto :noscripts

REM Find Python: prefer .tausik/venv
if exist "%SCRIPT_DIR%venv\Scripts\python.exe" (
    set "PYTHON=%SCRIPT_DIR%venv\Scripts\python.exe"
) else (
    set "PYTHON=python"
)

"%PYTHON%" "%SCRIPTS%\project.py" %*
exit /b %ERRORLEVEL%

:noscripts
echo Error: no scripts dir found ^(none of: %IDE_LIST% under .^<ide^>\scripts^) 1>&2
exit /b 1
