#!/usr/bin/env bash
# TAUSIK CLI wrapper — always uses .tausik/venv Python
# Generated by bootstrap. Do not edit manually.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Find scripts dir (claude / cursor / qwen / windsurf / codex)
SCRIPTS=""
for _ide in claude cursor qwen windsurf codex; do
    if [ -d "$PROJECT_DIR/.$_ide/scripts" ]; then
        SCRIPTS="$PROJECT_DIR/.$_ide/scripts"
        break
    fi
done
if [ -z "$SCRIPTS" ]; then
    echo "Error: no scripts dir found (.claude/.cursor/.qwen/.windsurf/.codex /scripts)" >&2
    exit 1
fi

# Find Python: prefer .tausik/venv, fallback to system
if [ -f "$SCRIPT_DIR/venv/bin/python" ]; then
    PYTHON="$SCRIPT_DIR/venv/bin/python"
elif [ -f "$SCRIPT_DIR/venv/Scripts/python.exe" ]; then
    PYTHON="$SCRIPT_DIR/venv/Scripts/python.exe"
else
    PYTHON="python"
fi

exec "$PYTHON" "$SCRIPTS/project.py" "$@"
