"""Append-only telemetry has a declared lifetime per file, and the window follows the reader.

MEASURED BEFORE: three sidecars in `.tausik`, 19 MiB between them — `routing_adherence` at 46,192
lines, `observed_coverage` at 54,000 and unwritten for twenty days, `token_metrics` at 8,216. Not
one line had ever been removed from any of them, and they sat beside DB backups that DO get pruned.
That asymmetry is what gave the omission away. AFTER: 11 MiB, both windows respected.

THE WINDOW FOLLOWS THE READER, not a round number, and the third file shows why that matters: its
reader needs the whole file, so it is not trimmed by age at all. A retention rule applied uniformly
would have destroyed a measurement in order to tidy a directory.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO / "scripts") not in sys.path:
    sys.path.insert(0, str(_REPO / "scripts"))

from telemetry_retention import (  # noqa: E402
    POLICIES,
    WINDOW_LINES,
    doctor_line,
    line_counts,
    over_window,
    truncate,
)

_RATCHET = json.loads((_REPO / "tausik" / "gates.json").read_text(encoding="utf-8"))["repo_hygiene"]


@pytest.fixture
def sidecars(tmp_path):
    """One file over its window, one under, one that is never trimmed by age."""
    (tmp_path / "token_metrics.jsonl").write_text(
        "".join(f'{{"n": {i}}}\n' for i in range(WINDOW_LINES + 500)), encoding="utf-8"
    )
    (tmp_path / "routing_adherence.jsonl").write_text('{"n": 1}\n' * 10, encoding="utf-8")
    (tmp_path / "observed_coverage.jsonl").write_text(
        "".join(f'{{"n": {i}}}\n' for i in range(WINDOW_LINES * 3)), encoding="utf-8"
    )
    return str(tmp_path)


def test_only_a_file_past_its_own_window_is_listed(sidecars):
    assert [p.name for p, _ in over_window(sidecars)] == ["token_metrics.jsonl"]


def test_the_file_whose_reader_needs_all_of_it_is_never_trimmed(sidecars):
    """THE NEGATIVE THAT MATTERS: `observed_coverage` is three windows long and must survive.

    Its whole content IS the measurement — which test touched which file — so a uniform retention
    rule would destroy a measurement in order to tidy a directory. It is regenerated by a run,
    not truncated.
    """
    before = line_counts(sidecars)["observed_coverage.jsonl"]
    truncate(sidecars)
    assert line_counts(sidecars)["observed_coverage.jsonl"] == before
    policy = next(p for p in POLICIES if p.name == "observed_coverage.jsonl")
    assert policy.keep_lines is None
    assert len(policy.reason) > 40, "a file exempted from retention has to say why"


def test_the_tail_is_kept_not_the_head(sidecars):
    """Telemetry is append-only, so the newest lines are the ones every reader wants.

    Trimming the other end would leave a file that looks healthy while answering about a past
    nobody asked about — worse than the unbounded file it replaced.
    """
    truncate(sidecars)
    lines = (Path(sidecars) / "token_metrics.jsonl").read_text(encoding="utf-8").splitlines()
    assert len(lines) == WINDOW_LINES
    assert json.loads(lines[-1])["n"] == WINDOW_LINES + 499, "the last record must survive"
    assert json.loads(lines[0])["n"] == 500, "the oldest 500 are what went"


def test_a_dry_run_reports_and_writes_nothing(sidecars):
    before = line_counts(sidecars)
    preview = truncate(sidecars, dry_run=True)
    assert preview == {"token_metrics.jsonl": (WINDOW_LINES + 500, WINDOW_LINES)}
    assert line_counts(sidecars) == before


def test_truncation_is_idempotent(sidecars):
    truncate(sidecars)
    assert truncate(sidecars) == {}, "a file at its window is not past it"


def test_the_doctor_line_warns_only_when_something_is_past_its_window(sidecars):
    assert doctor_line(sidecars)[0] == "warn"
    truncate(sidecars)
    level, detail = doctor_line(sidecars)
    assert level == "ok" and "within their window" in detail


def test_a_missing_directory_is_not_a_finding(tmp_path):
    """Absence of telemetry is absence, not a zero to warn about."""
    assert line_counts(str(tmp_path / "nope")) == {}
    assert doctor_line(str(tmp_path / "nope")) == ("ok", "no telemetry sidecars")


def test_the_live_tree_is_within_its_ratchet():
    """AC-3, with the threshold set where it can actually hold.

    The first version asserted "nothing past the reader's window" and was breached within minutes
    of the trim: a live session appends to these files, and the two were at 8024 and 8048 against
    a window of 8000. A threshold that ordinary work crosses is not a ratchet, it is a nuisance
    that gets switched off, so the ratchet watches ACCUMULATION — one window for the reader plus
    one for the session in progress — while the doctor line still mentions any excess.
    """
    from telemetry_retention import over_hard_limit

    past = over_hard_limit(str(_REPO / ".tausik"))
    assert len(past) <= _RATCHET["telemetry_sidecars"]["past_window"], [
        (p.name, n) for p, n in past
    ]


def test_the_hard_limit_leaves_room_for_the_session_in_progress():
    """The distinction between the two limits, pinned: the trim is eager, the ratchet is not."""
    from telemetry_retention import HARD_MULTIPLE, WINDOW_LINES

    assert HARD_MULTIPLE >= 2, "one window for the reader, one for the session writing right now"
    assert WINDOW_LINES * HARD_MULTIPLE > WINDOW_LINES


def test_every_policy_states_its_reason():
    """A window with no reason is a number somebody will round up next release."""
    for policy in POLICIES:
        assert len(policy.reason) > 40, f"{policy.name}: {policy.reason!r}"
