"""Manifest serialization: the mandatory key set, PyYAML access, YAML rendering.

Split out of ``renar_conformance`` for filesize-gate compliance, the way
``backend_schema_adapts`` was split out of ``backend_schema`` and
``verify_files_hash`` out of ``service_verification``. The parent stood at 499
lines against a cap of 500, and session #210 lost a closing iteration to it:
replacing one query line expanded it to six and the gate refused, so the
explanation had to be deleted to buy back the lines. A file with no headroom
taxes the next change in comments.

The seam is not invented for the occasion. ``_require_yaml`` was ALREADY being
imported across module boundaries — ``renar_export`` reaches into
``renar_conformance`` for it — so the primitive was shared while living in the
module that merely happened to define it first. Moving it here recognises that.

Public API is ``MANDATORY_FIELDS``, ``_require_yaml`` and ``render_yaml``; all
three are re-exported by ``renar_conformance`` so existing imports keep working
and no caller needs to know the split happened.

Behaviour is unchanged on purpose: the same key order, the same header text,
and the same RuntimeError when PyYAML is absent. This module moved code; it did
not get to have opinions about it.
"""

from __future__ import annotations

from typing import Any

from renar_mandatory_clauses import basis_header_lines
from renar_measurer_caveats import header_lines as caveats_header_lines

# Mandatory §13.4.2 keys a valid manifest must always carry.
MANDATORY_FIELDS = (
    "renar-version",
    "manifest-version",
    "manifest-id",
    "level",
    "assessment-mode",
    "assessment-date",
    "assessor",
    "mandatory-clauses-confirmed",
    "quality-gates",
    "substrate-capabilities",
    "spec-types-supported",
)


def _require_yaml():  # type: ignore[no-untyped-def]
    """Lazy PyYAML import — optional RENAR dependency, not a core CLI dep."""
    try:
        import yaml
    except ModuleNotFoundError as e:
        raise RuntimeError(
            "RENAR conformance/export needs PyYAML — install it: pip install pyyaml "
            "(it is an OPTIONAL dependency; the core TAUSIK CLI is stdlib-only)."
        ) from e
    return yaml


def render_yaml(manifest: dict[str, Any]) -> str:
    """Serialize to YAML 1.2 (§13.4.1). Stable key order, block style."""
    yaml = _require_yaml()
    header = (
        "# RENAR Conformance Manifest — auto-generated by `tausik renar conformance`.\n"
        "# Level is computed from live DB state (§13.4.3), not declared. Do not\n"
        "# hand-edit `level` / `mandatory-clauses-confirmed` — regenerate instead.\n"
        "#\n"
        "# §13.4.1 requires previous versions to survive as an audit journal.\n"
        "# The journal is THIS FILE'S GIT HISTORY: the substrate's V1 immutable\n"
        "# history (§3.3.1) is exactly the guarantee that clause asks for, so no\n"
        "# parallel file-history mechanism is kept. Read an earlier version with\n"
        "# `git log --follow -p RENAR-CONFORMANCE.yaml`; `replaces` names it.\n"
        "#\n" + basis_header_lines() + "#\n" + caveats_header_lines()
    )
    body: str = yaml.safe_dump(
        manifest, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    return header + body
